# Generated by Django 6.0.5 on 2026-05-29 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forum.question'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['target_type', 'target_id'], name='forum_like_target__434444_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'target_id', 'target_type')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'grade'], name='forum_quest_subject_865b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-likes_count'], name='forum_quest_likes_c_69c3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-answers_count'], name='forum_quest_answers_c68c80_idx'),
        ),
    ]
