# Generated by Django 6.0.5 on 2026-05-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('subject', models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('mathematics', 'Mathematics'), ('biology', 'Biology'), ('english', 'English'), ('nepali', 'Nepali'), ('social_studies', 'Social Studies'), ('computer_science', 'Computer Science')], max_length=20)),
                ('grade', models.CharField(choices=[('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=2)),
                ('resource_type', models.CharField(choices=[('textbook', 'Textbook'), ('notes', 'Notes'), ('past_paper', 'Past Paper'), ('practice_set', 'Practice Set')], max_length=15)),
                ('file_url', models.URLField(blank=True, default='', max_length=500)),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='File size in bytes')),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject', 'grade'], name='resources_r_subject_e757e3_idx'), models.Index(fields=['resource_type'], name='resources_r_resourc_1a6f3f_idx')],
            },
        ),
    ]
